use crate::{memory, tools};
use anyhow::Result;
use serde_json::{json,Value};
use std::{collections::HashSet, time::Duration};
use tokio::process::Command;

pub async fn report()->Result<Value>{let s=tools::system_snapshot().await?;let df=Command::new("df").args(["-P","/"]).output().await?;let line=String::from_utf8_lossy(&df.stdout).lines().nth(1).unwrap_or("").to_string();let cols:Vec<&str>=line.split_whitespace().collect();let disk_pct=cols.get(4).and_then(|x|x.trim_end_matches('%').parse::<u64>().ok()).unwrap_or(0);let mem_pct=if s.memory_total_bytes>0{(s.memory_used_bytes as f64/s.memory_total_bytes as f64*100.0).round() as u64}else{0};let mut alerts=Vec::new();if disk_pct>=90{alerts.push(json!({"severity":"critical","kind":"disk","message":format!("Root storage is {disk_pct}% full") }));}else if disk_pct>=82{alerts.push(json!({"severity":"warning","kind":"disk","message":format!("Root storage is {disk_pct}% full") }));}if mem_pct>=94{alerts.push(json!({"severity":"warning","kind":"memory","message":format!("Memory use is {mem_pct}%") }));}
let ps=Command::new("bash").args(["-lc","ps -eo comm,%cpu,%mem --sort=-%cpu | sed -n '2,7p'"]).output().await.ok().map(|o|String::from_utf8_lossy(&o.stdout).to_string()).unwrap_or_default();Ok(json!({"snapshot":s,"disk_percent":disk_pct,"memory_percent":mem_pct,"alerts":alerts,"top_processes":ps.lines().collect::<Vec<_>>() }))}
pub async fn monitor_forever(){let mut seen=HashSet::new();loop{if let Ok(r)=report().await{if let Some(alerts)=r.get("alerts").and_then(Value::as_array){for a in alerts{let sig=format!("{}:{}",a.get("kind").and_then(Value::as_str).unwrap_or("health"),a.get("severity").and_then(Value::as_str).unwrap_or("warning"));if seen.insert(sig.clone()){let _=memory::log_observation("health_alert",a);let msg=a.get("message").and_then(Value::as_str).unwrap_or("Fatir found a system health issue");let _=Command::new("notify-send").args(["Fatir system health",msg]).status().await;}}if alerts.is_empty(){seen.clear();}}}tokio::time::sleep(Duration::from_secs(600)).await;}}
